### ISSUE TITLE
Confirmation message and email for sender

### ISSUE THREAD

**Issue by derby** [cpham/acf-contact-form#2]
Hi, nice plugin, I thought about building an act form plugin but then I found yours ;-)
There are a few thing I still miss:
1. It would be nice to have the option to send a confirmation email to the user/ sender
2. After successfull form submission there is only the possibility to redirect to an internal page. It would be nice if either:
- form submission could be done via ajax and on success there will appear a customizable message.
- redirect could be a custom URL so that I can redirect to the same page and adding custom GET Variables to the URL, e.g. /contact?sent=success. Inside the page template I could then decide to show page content or success message.

Or is there maybe an action hook, that reacts on success?

**Comment by cpham** [comment]
Hi, Great ideas! I'll work on these over the holiday break :)

**Comment by derby** [comment]
Hi Christine, thanks for answering. Any news for this topic?
I also have another request but I think it is much more clear if I create a new issue for it. It relates to the ACF Pro field-wrapper attributes

**Comment by cpham** [comment]
Hi @derby 

This update is included in the newest beta release: https://github.com/cpham/acf-contact-form/releases/tag/0.3

Please read the documentation carefully.

MAJOR NOTE: I have removed the Return URL field from the ACF Forms options page. You can set this value from the shortcode itself. 

Example: 

`[acf_contact id="1" submit_value="Send Message" return="http://google.com/"]`
