### ISSUE TITLE
How does the Post Type work on ACF Forms?

### ISSUE THREAD

**Issue by elliottmangham** [cpham/acf-contact-form#21]
Hello,

More of a question than a bug, I don't fully understand what the "Post Type" option in "Basic Settings" is doing. Could you clarify, explain a little bit in more detail please?

I have it set to "custom_css" at the moment, which works - but I hate not understanding what it's doing so if anything ever breaks, I can resolve it!

Thanks a lot! Great plugin by the way. 

The more plugins for ACF the better! 👍 

![screen shot 2016-12-13 at 15 49 57](https://cloud.githubusercontent.com/assets/12933804/21147208/25e424f4-c14c-11e6-913b-9f9a837f76c3.png)

**Comment by cpham** [comment]
it just ties the form rules to that specific post type. what kind of information are you looking for?

**Comment by elliottmangham** [comment]
Does it not matter what the selection is?

**Comment by cpham** [comment]
yes it does matter, as it tells the form where to save the post in the correct post type.
