### ISSUE TITLE
Major console log issue when including <?php acf_form_head(); ?>

### ISSUE THREAD

**Issue by elliottmangham** [cpham/acf-contact-form#23]
Hello,

When I insert `<?php acf_form_head(); ?>` I receive these issues in my console log:

`JQMIGRATE: Migrate is installed, version 1.4.1
draggable.min.js?ver=1.11.4:11 Uncaught TypeError: Cannot read property 'mouse' of undefined
    at draggable.min.js?ver=1.11.4:11
    at draggable.min.js?ver=1.11.4:11
    at draggable.min.js?ver=1.11.4:11
(anonymous) @ draggable.min.js?ver=1.11.4:11
(anonymous) @ draggable.min.js?ver=1.11.4:11
(anonymous) @ draggable.min.js?ver=1.11.4:11
slider.min.js?ver=1.11.4:11 Uncaught TypeError: Cannot read property 'mouse' of undefined
    at slider.min.js?ver=1.11.4:11
    at slider.min.js?ver=1.11.4:11
    at slider.min.js?ver=1.11.4:11
(anonymous) @ slider.min.js?ver=1.11.4:11
(anonymous) @ slider.min.js?ver=1.11.4:11
(anonymous) @ slider.min.js?ver=1.11.4:11
iris.min.js?ver=1.0.7:4 Uncaught TypeError: a.widget is not a function
    at iris.min.js?ver=1.0.7:4
    at iris.min.js?ver=1.0.7:4
(anonymous) @ iris.min.js?ver=1.0.7:4
(anonymous) @ iris.min.js?ver=1.0.7:4
color-picker.min.js?ver=4.7:1 Uncaught TypeError: a.widget is not a function
    at color-picker.min.js?ver=4.7:1
    at color-picker.min.js?ver=4.7:1
(anonymous) @ color-picker.min.js?ver=4.7:1
(anonymous) @ color-picker.min.js?ver=4.7:1
acf-input.min.js?ver=5.5.2:2 Uncaught TypeError: Cannot set property 'locales' of undefined
    at Object.l10n_v3 (acf-input.min.js?ver=5.5.2:2)
    at Object.ready (acf-input.min.js?ver=5.5.2:2)
    at d (acf-input.min.js?ver=5.5.2:1)
    at Object.i (acf-input.min.js?ver=5.5.2:1)
    at Object.do_action (acf-input.min.js?ver=5.5.2:1)
    at HTMLDocument.<anonymous> (acf-input.min.js?ver=5.5.2:1)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)`

The form works well, but obviously this is a major concern!

Kindest regards

**Comment by cpham** [comment]
@elliottmangham acf_form_head is part of the acf plugin, not mine.
