### ISSUE TITLE
Email template not working

### ISSUE THREAD

**Issue by apitlekays** [cpham/acf-contact-form#3]
Hi cpham,

First of all, good job on this wonderful plugin! Saved me a lot of headache.

Should the email template be of any particular formal/structure? I've followed the instructions, but couldn't get the email sent using a template. It was okay without using any template. Is this a known bug, or it has got to do with the template itself?

**Comment by cpham** [comment]
can you walk me through what you did?

**Comment by apitlekays** [comment]
- I've created a folder, with name as specified , "acf-cf-templates".
- Then I created a file, named as specified, "acf-cf-Contact-Us.php".
- Inside that template file, I followed an email template here: https://gist.githubusercontent.com/theukedge/6670537/raw/8d02d68d36910e26051f7918eb803b06b726e0ab/gistfile1.php, but without the top and the bottom php codes, and generally a change to the content of the template to correspond to the ACF fields I've set up.
- the template appeared under the Template dropdown in the ACF Forms optin page. I choose that.
- tried to send a message, but no email received. When I deselect the email template and tried to send a message again, the message got through.
- that led me to think that there might be a specific email template structure that this plugin rely on to make it work. 

Please advise.

**Comment by cpham** [comment]
can you try it without the html/body/head tags?

**Comment by cpham** [comment]
Also, where does $author come from?

**Comment by cpham** [comment]
@apitlekays any updates?
