### ISSUE TITLE
field-wrapper attributes

### ISSUE THREAD

**Issue by derby** [cpham/acf-contact-form#4]
Hi again,

fields in the frontend forms do no contain the wrapper-attributes (id, class, width) specified in the field group.
This does not seem to be very complicated, so I can try to add this feature. Can you give me a hint for a good implementation?

**Comment by cpham** [comment]
hmmm, that doesn't seem quite right because I'm using the class attribute to allow you to add the akismet classes.

As far as I know, this still works. Also, i'm just using the acf_form() function from the ACF documentation, nothing special.

**Comment by cpham** [comment]
![screen shot 2016-02-04 at 8 49 43 am](https://cloud.githubusercontent.com/assets/380172/12818382/4df5e6fc-cb1c-11e5-8a16-17a1e3208a5c.png)

**Comment by derby** [comment]
hmmm that's weird, maybe there is a problem with other plugins. I will check and report  tomorrow ...

**Comment by cpham** [comment]
any updates @derby ?

**Comment by derby** [comment]
Hi, sorry for my late reply and for creating this issue. This was absolutely my stupid fault. I modified the wrong field group   ;-(
