### ISSUE TITLE
Hidden field

### ISSUE THREAD

**Issue by PUncle** [cpham/acf-contact-form#5]
Hey,

I really like what you have done with this so far - its really cool.

I just wanted to ask if you could think of a way to add a hidden field to the form before it's submitted. In my case all I want to do is add the title of the current post to the form so it can be displayed along with the results.

I imagine the simplest way would be to write a function that echos get_the_title() into the results somehow, but I'm not sure where to start with that.

Any ideas?

Thanks!

**Comment by cpham** [comment]
Hi @PUncle,
You can add a text field to the field set and hide it with css. Then use javascript to populate the value of that field on the page.

**Comment by PUncle** [comment]
@cpham Good plan - thanks for the idea.

I started playing with [ACF Enhanced Message Field](https://github.com/wp-plugins/acf-enhanced-message-field) which allows the use of php in ACF message fields, which got me part of the way there, but of course this wasn't handled by ACF Contact Form, so falling back to js seems sensible.

Anyway, keep up the great work on this. I'm really liking it!

Thanks!
