### ISSUE TITLE
Need to submit twice to send it

### ISSUE THREAD

**Issue by despecial** [cpham/acf-contact-form#7]
Hi. Thanks for the plugin. 
Unfortunately there seems to be a hickup.

When submitting the form the loader shows up and nothing happens.
After clicking the submit button another time the form is send.

Can you confirm this?

edit: looks like an issue with the theme. it prevents the default action on buttons. weird ;)

**Comment by cpham** [comment]
Okay, thanks for updating. I'll close this as it's an issue with your theme and not the plugin.
