### ISSUE TITLE
Suggestion for Mail Preview

### ISSUE THREAD

**Issue by derby** [cpham/acf-contact-form#9]
Hi Christine,

I created an action for previewing my mail templates. It works like this:
For Preview you can go to any frontpage on your website, all you have to do is append a GET Variable to the URL: ?acf-mail-preview=[name-of-your-template-file]
Example:
Your website URL is: http://website.com
Your ACF-Mail-Template is: acf-cf-website-admin.php
Then you can preview the Mail like this: http://website.com?acf-mail-preview=acf-cf-website-admin
All you have to do is inserting the following code e.g. to your functions.php or put it into your plugin:
```
add_action('template_redirect', function()
{
  if ( !isset($_GET['acf-mail-preview']) || empty($_GET['acf-mail-preview']) ) return;
  $mail_template = get_template_directory().'/acf-cf-templates/acf-cf-'.$_GET['acf-mail-preview'].'.php';
  if ( !file_exists($mail_template) ) return;
  include_once($mail_template);
  die();
});
```
Since Mail Preview is on your roadmap I thought you could create an iframe on the ACF-Forms Options Page or simply create a preview link which contains the GET Variable.

Best regards, Torben

**Comment by cpham** [comment]
This actually already is part of the current release - the url is different but it works the same. I haven't linked the preview anywhere in the admin so that you can get to it easily, and that's what the to-do item is for.

**Comment by derby** [comment]
Ah ok very nice! You are much more faster than me ;-)

**Comment by cpham** [comment]
I've made the preview link available in the edit post screen
